name: RPGOverhaul
main: com.SinfulPixel.RPGOverhaul.RPGOverhaul
version: 1.0
description: A Complete RPG Overhaul for Minecraft
author: Min3CraftDud3
website: http://www.SinfulPixel.com
commands:
  rpgreload:
    description: "Reloads RPGOverhaul"
  soulbound:
    description: "Bring up the soulbound item actions."
  saveitem:
    description: "Saves Item to File."